### ISSUE TITLE
Is `addEvent`abstraction needed?

### ISSUE THREAD

**Issue by sarbbottam** [yahoo/hertz#1]
Is [`addEvent`](https://github.com/yahoo/hertz/blob/master/index.html#L79-L91) abstraction needed?

``` js
addEvent = function(elm, event, action) {
  if (elm.addEventListener) {
    elm.addEventListener(event, action, false);
  }
  else if (elm.attachEvent) {
    elm.attachEvent('on' + event, action);
  }
  else {
    elm['on' + event] = action;
  }
};
```

If the browser is not supporting `addEventListener`, I doubt it would support [`AudioContext`](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext#Browser_compatibility) 😄

**Comment by imbrianj** [comment]
Wait - you opened an issue for being too defensive?  :stuck_out_tongue:

**Comment by imbrianj** [comment]
https://github.com/yahoo/hertz/commit/5173a36b104adc5ca4f7213bfb52724a6b0ebd7d
